{{- if .Values.external_secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
    product: spi
    facility: {{ include "app.fullname" . }}
spec:
  data:
  - remoteRef:
      key: {{ include "app.fullname" . }}-signingKeySecret
      property: signingKey
    secretKey: signingKey
  secretStoreRef:
    name: pi-aws-secretstore
    kind: SecretStore
  target:
    name: {{ include "app.fullname" . }}-external-secret
    template:
      metadata: {}
status:
  refreshTime: null
{{- end }}
