apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-app
  namespace: spi
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.value_analysis_iam_arn_app }}"
imagePullSecrets:
  - name: docker-secret
