apiVersion: v1
kind: ServiceAccount
metadata:
  name: value-analysis-admin
  namespace: spi
  labels:
    {{- include "migration.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.value_analysis_iam_arn_migration }}"
imagePullSecrets:
  - name: docker-secret
